# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='filmactor',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filmcategory',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmdirector',
            name='director',
        ),
        migrations.RemoveField(
            model_name='filmdirector',
            name='film',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='actor', to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='categorys',
            field=models.ManyToManyField(related_name='category', to='movies.Category'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(related_name='director', to='movies.Director'),
        ),
        migrations.AlterField(
            model_name='showtime_detail',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='FilmActor',
        ),
        migrations.DeleteModel(
            name='FilmCategory',
        ),
        migrations.DeleteModel(
            name='FilmDirector',
        ),
    ]
