# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20171017_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='actors',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='categorys',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='directors',
            new_name='director',
        ),
    ]
