# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20171017_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birtday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
